'use strict';
const $=id=>document.getElementById(id),status=text=>$('status').textContent=text;
function resizeCanvas(){const canvas=$('camerafeed'),ratio=Math.min(window.devicePixelRatio||1,2);canvas.width=Math.round(window.innerWidth*ratio);canvas.height=Math.round(window.innerHeight*ratio);}window.addEventListener('resize',resizeCanvas);resizeCanvas();
let ready=false,running=false,scene,camera,reticle,hit=null,gift=null,placed=false,stable=0,lastHit=null;
function resetPlacement(){if(gift){scene.remove(gift);gift.traverse(o=>{o.geometry?.dispose();if(o.material)o.material.dispose();});gift=null;}placed=false;hit=null;lastHit=null;stable=0;$('place').disabled=true;$('clear').disabled=true;status('床・台をゆっくり映して、中央の輪が出るのを待ってください。');}
function buildGift(height){const group=new THREE.Group(),teal=new THREE.MeshStandardMaterial({color:0x087d8b,roughness:.35}),gold=new THREE.MeshStandardMaterial({color:0xf1d291,metalness:.35,roughness:.35});
const add=(x,y,z,sx,sy,sz,material)=>{const mesh=new THREE.Mesh(new THREE.BoxGeometry(sx,sy,sz),material.clone());mesh.position.set(x,y,z);group.add(mesh);};
add(0,.42,0,.8,.84,.8,teal);add(0,.85,0,.86,.07,.86,teal);add(0,.43,0,.13,.87,.815,gold);add(0,.43,0,.815,.87,.13,gold);
for(const sign of [-1,1]){const loop=new THREE.Mesh(new THREE.TorusGeometry(.15,.025,8,24),gold.clone());loop.position.set(sign*.12,.95,0);loop.rotation.y=sign*.45;group.add(loop);}
group.scale.setScalar(height/1.125);return group;}
function placeGift(){if(!running||placed||!hit||stable<4)return;gift=buildGift(Number($('size').value));gift.position.copy(hit);scene.add(gift);placed=true;reticle.visible=false;$('place').disabled=true;$('clear').disabled=false;status('配置しました。スマホを左右・前後にゆっくり動かし、台・床に対する位置を確認してください。');}
const pipeline={name:'winter-world-placement',onStart:()=>{({scene,camera}=XR8.Threejs.xrScene());scene.add(new THREE.HemisphereLight(0xffffff,0x344852,1));const light=new THREE.DirectionalLight(0xffffff,.8);light.position.set(3,8,4);scene.add(light);camera.position.set(0,2,2);XR8.XrController.updateCameraProjectionMatrix({origin:camera.position,facing:camera.quaternion});
reticle=new THREE.Mesh(new THREE.RingGeometry(.08,.10,32),new THREE.MeshBasicMaterial({color:0xf1d291,side:THREE.DoubleSide}));reticle.rotation.x=-Math.PI/2;reticle.visible=false;scene.add(reticle);running=true;$('start').hidden=true;status('床・台をゆっくり映して、中央の輪が出るのを待ってください。');},
onUpdate:()=>{if(!running||placed)return;let hits=[];try{hits=XR8.XrController.hitTest(.5,.55,['DETECTED_SURFACE','ESTIMATED_SURFACE']);}catch(e){status('面検出APIのエラー：'+(e.message||String(e)));hit=null;reticle.visible=false;$('place').disabled=true;return;}const found=hits.find(h=>h.position&&[h.position.x,h.position.y,h.position.z].every(Number.isFinite));if(!found){status('カメラ起動済み / 面候補0件。床の模様をゆっくり映してください。台より先に床でお試しください。');hit=null;lastHit=null;stable=0;reticle.visible=false;$('place').disabled=true;return;}const next=new THREE.Vector3(found.position.x,found.position.y,found.position.z);stable=lastHit&&lastHit.distanceTo(next)<.035?stable+1:1;lastHit=next.clone();hit=next;reticle.position.copy(next);reticle.position.y+=.002;reticle.visible=true;if(stable<4)status('面候補あり / 位置を確認中…');$('place').disabled=stable<4;if(stable>=4)status('配置できる面を検出しました。「ここに置く」を押してください。');},
onException:e=>{status('ARを開始できませんでした：'+(e.message||String(e)));$('start').hidden=false;$('start').disabled=false;},onCameraStatusChange:({status:s})=>{if(s==='failed')status('カメラを許可し、SafariでHTTPSページを開いてください。');}};
function engineReady(){if(ready)return;ready=true;$('start').disabled=false;$('start').textContent='空間固定テストを開始';}
window.addEventListener('xrloaded',engineReady);if(window.XR8)engineReady();
$('start').onclick=async()=>{if(!ready||running)return;if(!window.isSecureContext){status('HTTPSの公開ページで開いてください。');return;}$('start').disabled=true;try{if(typeof DeviceMotionEvent!=='undefined'&&DeviceMotionEvent.requestPermission){const permission=await DeviceMotionEvent.requestPermission();if(permission!=='granted')throw new Error('モーションの許可が必要です');}XR8.XrController.configure({disableWorldTracking:false,scale:'absolute'});XR8.addCameraPipelineModules([XR8.GlTextureRenderer.pipelineModule(),XR8.Threejs.pipelineModule(),XR8.XrController.pipelineModule(),pipeline]);await XR8.run({canvas:$('camerafeed')});}catch(e){pipeline.onException(e);}};
$('place').onclick=placeGift;$('clear').onclick=resetPlacement;$('size').onchange=()=>{if(gift)gift.scale.setScalar(Number($('size').value)/1.125);};
window.addEventListener('pagehide',()=>{if(window.XR8&&running)XR8.stop();});
setTimeout(()=>{if(!ready)status('エンジンを読み込めません。ネット接続を確認してページを再読み込みしてください。');},25000);
